version: "3.9"
services:
  pi-hole:
    container_name: pi-hole
    restart: always
    image: pihole/pihole:latest@sha256:e3bb67ee283afee5fffd1d3ea8b95c4a2bf3aa445f955d4e5f3947d72904d580
    ports:
      - "8053:53/tcp"
      - "8053:53/udp"
      - "8067:67/udp"
      - "8080:80"
      - "8443:443"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
      # PROXY_LOCATION: ${PROXY_LOCATION}
      # VIRTUAL_HOST: ${VIRTUAL_HOST}
    volumes:
      - './data/etc-pihole/:/etc/pihole/'
      - './data/etc-dnsmasq.d/:/etc/dnsmasq.d/'

  homeassistant:
    container_name: homeassistant
    restart: unless-stopped
    image: ghcr.io/home-assistant/home-assistant:stable@sha256:48773146b3b7f7d4811426a33044a322e8e4fcda97b9ed9a6b37d7e5b649af0b
    ports:
      - "8123:8123"
    volumes:
      - './data/homeassistant:/config'
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: ${TZ}
    network_mode: host
  
  uptime-kuma:
    container_name: uptime-kuma
    restart: always
    image: louislam/uptime-kuma:latest@sha256:c326fd83d8da2d8fff3feb0e47433546139513bd823d9accc12977176b05b31f
    ports:
      - "3001:3001"
    volumes:
      - './data/uptime-kuma:/app/data'

  myspeed:
    container_name: myspeed
    restart: always
    image: germannewsmaker/myspeed:latest@sha256:ae5e8f79c76dc695a6bab86cf9a0a6ab0dcf8ebf4e7018e04c47e5af0200c847
    ports:
      - "5216:5216"
    volumes:
      - './data/myspeed:/app/data'

  nextcloud:
    container_name: nextcloud
    restart: always
    image: nextcloud:latest@sha256:ee6e559f740416b8f34bd1dc8fc9a0f1c90d00800fdfba3b1d493e86ebecd5ae
    ports:
      - "10081:80"
      - "10443:443"
    volumes:
      - './data/nextcloud:/var/www/html'

  syncthing:
    container_name: syncthing
    restart: always
    image: linuxserver/syncthing:latest@sha256:1a7cb8189b9a231ec966bf44de773d0ce33a3147af59c1bd9a20cfe113e6cce1
    ports:
      - "8384:8384"
      - "22000:22000"
      - "22000:22000/udp"
      - "21027:21027/udp"
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: ${TZ}
    volumes:
      - './data/syncthing:/config'
      - './files:/mnt/data'

  netbootxyz:
    container_name: netbootxyz
    restart: always
    image: ghcr.io/netbootxyz/netbootxyz:latest@sha256:9e37f3844ef348d0c17d1f8d111e63e1d7b6e98e4d14f25935e3f475b06c5994
    ports:
      - 3000:3000
      - 69:69/udp
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: ${TZ}
    volumes:
      - ./data/netbootxyz:/config

  # shlinkio:
  #   image: shlinkio/shlink:stable
  #   container_name: shlink
  #   restart: unless-stopped
  #   env_file: .env
  #   ports:
  #     - "8090:8080"

  # unbound:
  #   container_name: unbound
  #   restart: always
  #   image: mvance/unbound:latest@sha256:8e6cbf0485887c4c7581d522d61e0bcd9350f7ea16aa420f8b2fbfcccc957790
  #   ports:
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #   environment:
  #     TZ: ${TZ}
  #   volumes:
  #     - './data/unbound:/opt/unbound/etc/unbound'

  # wireguard:
  #   container_name: wireguard
  #   restart: always
  #   image: linuxserver/wireguard:latest@sha256:9463aadffb1e01bc281f66bebb21d5ce739d059c59f21494676598629fd61933
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   environment:
  #     PUID: $PUID
  #     PGID: $PGID
  #     TZ: ${TZ}
  #   volumes:
  #     - './data/wireguard:/config'
  #     - '/lib/modules:/lib/modules:ro'