name: Image digest update

on:
  workflow_dispatch:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

    - uses: chainguard-dev/digestabot@3830b931642989ef391e6db4c0bbcd2bc20d064f
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
